# Generated by Django 5.1.5 on 2025-01-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('stock', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.supplier')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
